spring:
  profiles:
    active: uat
  application:
    name: config-server  # 应用名称

eureka:
  instance:
    hostname: ${spring.application.name}
    instance-id: ${eureka.instance.hostname}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
